### ISSUE TITLE
Wrong parameter name for python_instance_main.py when using the TLS

### ISSUE THREAD

**Issue by rhollosy** [streamnative/function-mesh#438]
In case of python function, the operator generates parameters for the python_instance_main.py. One of the arguments that the script takes is **--tls_allow_insecure_connection**, however operator generates --tls_allow_insecure instead, which prevents the python function from starting up.

**Comment by jiangpengcheng** [comment]
the argparse of python allow abbrev by default, see: https://docs.python.org/3/library/argparse.html#allow-abbrev

so `--tls_allow_inscure` will be passed to `--tls_allow_insecure_connection`, we can even pass the `--tls_allow` to the `python_instance_main.py`

**Comment by rhollosy** [comment]
You are right with this abbrev. I finally found what is wrong:

Initially I was missing the tlsAllowInsecureConnection environment variable, which caused the issue in the execution of ```python_instance_main.py```. The option ```--tls_allow_insecure``` expects also a value there.

However once the ```tlsAllowInsecureConnection``` environment variable was defined, it caused a problem one step before i.e. in execution of ```pulsar-admin --tls-allow-insecure $tlsAllowInsecureConnection```

```pulsar-admin``` doesn't expect the value after ```--tls-allow-insecure``` there. e.g.
```
./pulsar-admin --tls-allow-insecure false topics list public/default
Was passed main parameter 'false' but no main parameter was defined in your arg class
```
The same counts for ```--tls-enable-hostname-verification``` option. What needs to be done is to omit passing of $tlsAllowInsecureConnection and $tlsHostnameVerificationEnable values in the pulsar-admin call.

**Comment by jiangpengcheng** [comment]
@rhollosy thanks for addressing!
it's a known issue: https://github.com/streamnative/function-mesh/issues/388, and it's already resolved by #414

could you try with FM v0.4.0, and use `tlsConfig` instead of `tlsSecret` to set tls related parameters? like below:

```YAML
  pulsar:
    pulsarConfig: "YOUR-PULSAR-CONFIGMAP"
    tlsConfig:
      enabled: true
      allowInsecure: false
      hostnameVerification: true
      # certSecretName: the name of YOUR-TLS-TRUST-CERT-SECRET if you want to pass the `--tls-trust-cert-path`
      # certSecretKey: the key of your YOUR-TLS-TRUST-CERT-SECRET-NAME
```

we will update the related doc ASAP

**Comment by rhollosy** [comment]
@jiangpengcheng  thank you very much for the guidance. I upgraded to FM v0.4.0 like you suggested and reconfigured the Function. However it still didn't solve the issue. I noticed, that the generated command is different, now it contains this fragment:
```
--tls-allow-insecure ${tlsAllowInsecureConnection:-false} --tls-enable-hostname-verification ${tlsHostnameVerificationEnable:-true}
```
which means that the value of the environment variable or ```false``` is injected. I believe the values shouldn't be there, like I showed in the previous comment. Obviously I'm getting the same error.

**Comment by jiangpengcheng** [comment]
did you still use the `tlsSecret` under the `.spec.pulsar` section?

**Comment by rhollosy** [comment]
sure I didn't. But you are right that it is related to this part of the configuration. Maybe there is something wrong with my FM installation or it is a different issue:
I prepared a YAML file:
```
spec:
  pulsar:
    authSecret: client-auth-secret
    pulsarConfig: prod01-pulsar-config
    tlsConfig:
      enabled: true
      allowInsecure: false
      hostnameVerification: true
      caSecretName: prod01-pulsar-ca-tls
      caSecretKey: ca.crt
```
then I applied it with ```oc apply -f tls-new-func.yaml```, seemingly succesfuly.
When I looked back at the live configuration, the whole tlsConfig block was missing and only the authSecret and pulsarConfig items remained. I tried both creating the function from scratch and updating the existing function.

The operator is raising an error:

2022-08-02T07:41:08.322Z	ERROR	controllers.Function	error create or update statefulSet workload	{"namespace": "function-mesh-system", "name": "tls-new-func-function", "error": "Operation cannot be fulfilled on statefulsets.apps \"tls-new-func-function\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
	github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).ApplyFunctionStatefulSet
	github.com/streamnative/function-mesh/controllers/function.go:94
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).Reconcile
	github.com/streamnative/function-mesh/controllers/function_controller.go:94
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90

I'll keep trying. Thank you.

**Comment by rhollosy** [comment]
Sure I'm not using the tlsSecret anymore. But I found out that something is wrong on my side and I don't wanna misguide you. This is the excerpt of my spec. 
```
spec:
  pulsar:
    authSecret: client-auth-secret
    pulsarConfig: prod01-pulsar-config
    tlsConfig:
      enabled: true
      allowInsecure: false
      hostnameVerification: true
      certSecretName: prod01-pulsar-ca-tls
      certSecretKey: ca.crt
```
I prepared the pristine yaml file and applied it with ```oc apply```, seemingly everything was OK. Then I noticed operator raising errors. When I looked back at the live configuration, the whole tlsConfig block was missing. The operator produced this error log:
```
 2022-08-02T07:41:08.322Z	ERROR	controllers.Function	error create or update statefulSet workload	{"namespace": "function-mesh-system", "name": "tls-new-func-function", "error": "Operation cannot be fulfilled on statefulsets.apps \"tls-new-func-function\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
	github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).ApplyFunctionStatefulSet
	github.com/streamnative/function-mesh/controllers/function.go:94
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).Reconcile
	github.com/streamnative/function-mesh/controllers/function_controller.go:94
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
```
I tried creating the function from scratch as well as updating an existing function.
I'll keep searching for an root cause. Thank you.

**Comment by jiangpengcheng** [comment]
do you mean the `kubectl get function tls-new-func-function -o yaml` still using the `tlsSecret` config instead of the `tlsConfig` after you apply the new YAML? that looks strange, it's k8s' job to update the `function`.

and about the `Operation cannot be fulfilled on statefulsets.apps` error, I have faced it sometimes too, but it looks like doesn't cause any failures(anyway, this error should be fixed)

**Comment by jiangpengcheng** [comment]
@rhollosy 
could you please provide your YAML file after erasing sensitive info? I can try it in my local env

**Comment by rhollosy** [comment]
No, the ```oc get``` just gives me the configuration without the tlsConfig block. So it looks like this:
```
  pulsar:
    authSecret: client-auth-secret
    pulsarConfig: prod01-pulsar-config
```
This is the redacted spec:
```
apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: tls-new-func
  namespace: function-mesh-system
spec:
  autoAck: true
  className: ExclamationFunction.ExclamationFunction
  clusterName: prod01
  forwardSourceMessageProperty: true
  input:
    topics:
    - persistent://public/default/pyinstance3
    typeClassName: '[B'
  logTopic: persistent://public/default/py-function-logs
  maxPendingAsyncRequests: 1000
  maxReplicas: 1
  name: tls-function-simple
  namespace: default
  output:
    topic: persistent://public/default/pyinstance4
    typeClassName: '[B'
  pod:
    serviceAccountName: function-worker
    volumes:
    - name: token-volume
      secret:
        items:
        - key: TOKEN
          path: token
        optional: false
        secretName: SOME_TOKEN_SECRET
  processingGuarantee: atleast_once
  pulsar:
    authSecret: client-auth-secret
    pulsarConfig: prod01-pulsar-config
    tlsConfig:
      enabled: true
      allowInsecure: false
      hostnameVerification: true
      certSecretName: prod01-pulsar-ca-tls
      certSecretKey: ca.crt
  python:
    py: ExclamationFunction.zip
    pyLocation: SOME_LINK
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 1100M
    requests:
      cpu: 100m
      memory: 1G
  secretsMap:
    OTEL_EXPORTER_JAEGER_AGENT_HOST:
      key: JAEGER_AGENT_HOSTNAME
      path: func-env-secret
    OTEL_EXPORTER_JAEGER_AGENT_PORT:
      key: JAEGER_AGENT_PORT
      path: func-env-secret
  tenant: public
  volumeMounts:
  - mountPath: /var/run/secrets/pulsar/auth-token
    name: token-volume
```

**Comment by rhollosy** [comment]
@jiangpengcheng please consider this closed. I found out that the automated argocd deployment didn't update the CRDs, so I have to fix that first. thank you for your support. I believe after fixing this issue, everything will work just fine.
